language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get install git
before_script:
    - bash -c 'sudo mkdir /var/git; sudo chown $USER /var/git'
script: python setup.py coverage
after_success:
    - coverage report
    - pip install python-coveralls && coveralls
